### ISSUE TITLE
ImportError: No module named 'gvm'

### ISSUE THREAD

**Issue by davidak** [greenbone/gvm-tools#143]
### Expected behavior

Setup using pip works. Install on unsupported python versions should print error.

### Current behavior

Setup using pip fails.

#### Python 2.7

```
[davidak@ethmoid:~/code/gvm-tools]$ docker run -ti --rm -v $PWD:/root/code python:2.7 bash
root@0b889fd71820:/# cd /root/code/
root@0b889fd71820:~/code# pip install .
Processing /root/code
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7ld4Vi/setup.py", line 27, in <module>
        version = __import__('gvmtools').get_version()
      File "gvmtools/__init__.py", line 22, in <module>
        from gvm.utils import get_version_string
    ImportError: No module named gvm.utils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-7ld4Vi/
```

#### Python 3.4

```
[davidak@ethmoid:~/code/gvm-tools]$ docker run -ti --rm -v $PWD:/root/code python:3.4 bash
root@cdd0bcd63f62:/# cd /root/code/
root@cdd0bcd63f62:~/code# pip install .
Processing /root/code
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-nf8a9fgh/setup.py", line 27, in <module>
        version = __import__('gvmtools').get_version()
      File "/tmp/pip-req-build-nf8a9fgh/gvmtools/__init__.py", line 22, in <module>
        from gvm.utils import get_version_string
    ImportError: No module named 'gvm'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-nf8a9fgh/
```

Same on Python 3.5.

### GVM versions

**gvm-tools:** master (0ccb58506428d69805c5bee4ec923881095f3d9e)

### Environment
**Operating system:** python docker image

**Installation method / source:** pip using source

**Comment by davidak** [comment]
Installing using pip is the most popular way, so it should work.

The install itself shouldn't depend on external dependencies.
