### ISSUE TITLE
[1.4.1] Uncatched python exceptions

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gvm-tools#191]
When click on cancel at the log in dialog then this exception will thrown:
```
Traceback (most recent call last):
  File "/bin/gvm-dialog", line 11, in <module>
    load_entry_point('gvm-tools==1.4.1', 'console_scripts', 'gvm-dialog')()
  File "/usr/lib/python3.6/site-packages/gmp/clients/gvm_dialog.py", line 146, in main
    gmp.authenticate(credentials[0], credentials[1])
IndexError: list index out of range

```
Enter an wrong password then another exception will thrown:
```
Traceback (most recent call last):
  File "/bin/gvm-dialog", line 11, in <module>
    load_entry_point('gvm-tools==1.4.1', 'console_scripts', 'gvm-dialog')()
  File "/usr/lib/python3.6/site-packages/gmp/clients/gvm_dialog.py", line 146, in main
    gmp.authenticate(credentials[0], credentials[1])
  File "/usr/lib/python3.6/site-packages/gmp/gvm_connection.py", line 220, in authenticate
    return self.read()
  File "/usr/lib/python3.6/site-packages/gmp/gvm_connection.py", line 113, in read
    self.checkCommandStatus(response)
  File "/usr/lib/python3.6/site-packages/gmp/gvm_connection.py", line 166, in checkCommandStatus
    raise GMPError(status_text)
gmp.gvm_connection.GMPError: Authentication failed
```

Expected:
That the exceptions will be catched.

**Comment by bjoernricks** [comment]
Hi,

gvm-dialog is experimental in 1.4.1 and will be removed with 2.0. So I am sorry this issue wont get fixed from our side anymore.
