### ISSUE TITLE
gmp.get_version() return error

### ISSUE THREAD

**Issue by jessie4736** [greenbone/gvm-tools#192]
Hello, 

i need some help, here is my code:

-------------------------------------
!/usr/bin python3.6
 -*- coding: utf-8 -*-

from gvm.connections import UnixSocketConnection
from gvm.protocols.latest import Gmp
from gvm.transforms import EtreeTransform
from gvm.xml import pretty_print

connection = UnixSocketConnection()
transform = EtreeTransform()
gmp = Gmp(connection, transform=transform)

version = gmp.get_version()

pretty_print(version)

and output is:
-------------------------------------
Traceback (most recent call last):
  File "gmp.py", line 4, in <module>
    from gvm.connections import UnixSocketConnection
  File "/usr/lib/python2.7/site-packages/gvm/connections.py", line 172
    def __init__(self, *, timeout=DEFAULT_TIMEOUT, hostname='127.0.0.1',
                        ^
SyntaxError: invalid syntax
[root@p21210v tianna]# python3 gmp.py 
Traceback (most recent call last):
  File "gmp.py", line 14, in <module>
    version = gmp.get_version()
  File "/usr/lib/python3.4/site-packages/gvm/protocols/gmpv7.py", line 3268, in get_version
    return self._send_xml_command(XmlCommand('get_version'))
  File "/usr/lib/python3.4/site-packages/gvm/protocols/base.py", line 77, in _send_xml_command
    return self.send_command(xmlcmd.to_string())
  File "/usr/lib/python3.4/site-packages/gvm/protocols/base.py", line 131, in send_command
    raise e
  File "/usr/lib/python3.4/site-packages/gvm/protocols/base.py", line 127, in send_command
    self._send(cmd)
  File "/usr/lib/python3.4/site-packages/gvm/protocols/base.py", line 62, in _send
    self.connect()
  File "/usr/lib/python3.4/site-packages/gvm/protocols/base.py", line 98, in connect
    self._connection.connect()
  File "/usr/lib/python3.4/site-packages/gvm/connections.py", line 310, in connect
    self._socket.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

some env:
----------------------------------

ps axu | grep gvmd
root      5082  0.0  0.0 112704   976 pts/2    R+   19:57   0:00 grep --color=auto gvmd
root     14816  0.0  0.4 422948 75512 ?        SL   Jun03   0:40 gvmd: Waiting for incoming connections

-----------------------------------
gvmd.sock is in /run/

THANKS!

**Comment by jessie4736** [comment]
###and:
[root@test]# gvm-cli socket --xml "<get_version/>"
[Errno 2] No such file or directory

**Comment by rgrewe** [comment]
Try this. 
gvm-cli socket --socketpath /run/gvmd.sock --xml '<get_version/>'

**Comment by cfi-gb** [comment]
As this is more about the usage of gvm-cli i'm closing this issue for now. I would suggest to move further discussions to https://community.greenbone.net/c/gmp and only use this bugtrackers if an actual bug was found.

**Comment by bjoernricks** [comment]
As @rgrewe mentioned you need to specify the path to the openvasmd/gvmd socket. There are several threads about this at https://community.greenbone.net/c/gmp

**Comment by jessie4736** [comment]
@rgrewe
thanks, it works
