### ISSUE TITLE
gvm-cli: Incorrect documentation on providing an XML file as an input

### ISSUE THREAD

**Issue by elfakyn** [greenbone/gvm-tools#429]
The documentation on gvm-cli says:

> Read a file with GMP commands and return the result:
> `gvm-cli --gmp-username foo --gmp-password bar socket < myfile.xml`

However, when I attempt to do that, I receive the following error:

```bash
root@gvm-openvas-7f8c9f667b-s2hpc:/# su gvm
$ gvm-cli --gmp-username=admin --gmp-password=${PASSWORD} socket --sockpath /usr/local/var/run/gvmd.sock < create_scan_config.xml
Traceback (most recent call last):
  File "/usr/local/bin/gvm-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gvmtools/cli.py", line 104, in main
    if len(xml) == 0:
TypeError: object of type 'NoneType' has no len()
```

However, when I remove the `<` it is operating as expected:

```
$ gvm-cli --gmp-username=admin --gmp-password=${PASSWORD} socket --sockpath /usr/local/var/run/gvmd.sock create_scan_config.xml
<create_config_response status="201" status_text="OK, resource created" id="e6ae4e72-6e78-4cb0-a936-2fdac437387f"><config id="e6ae4e72-6e78-4cb0-a936-2fdac437387f"><name>Full and fast Import2 2</name></config></create_config_response>
```

I am running gvm-cli 21.1.0 (API version 21.4.0).

I have also confirmed this by inspecting the latest source code of [cli.py])https://github.com/greenbone/gvm-tools/blob/master/gvmtools/cli.py#L85); it is expecting the XML file name as a parameter, not to pipe in the file contents.

**Comment by elfakyn** [comment]
thank you!! that was fast!
